
<link rel="stylesheet" href="/css/path.css">
<script src='/js/path.js'></script>

<script>
$(document).ready(function(){

	drawPath();

	$("div.device").mouseenter(function(){

		$(".route").remove();
		drawPath();
		$(".route").hide();
		target = $(this).attr('toggle');
		$('#' + target).show();
	});

});

</script>

<body>


<div class="device" toggle="device1"></div>
<div class="device" toggle="device2"></div>



<div class="path"></div>



<div class="sub"></div>
<div class="sub"></div>
<div class="sub"></div>



</body>

<!--
<svg height="210" width="500">
  <line x1="190" y1="29" x2="200" y2="200" style="stroke:rgb(255,0,0);stroke-width:1" />
  Sorry, your browser does not support inline SVG.
</svg>
-->