
<link rel="stylesheet" href="/css/path.css">
<script src='/js/path.js'></script>

<script>
$(document).ready(function(){

	drawPath();

	$("div.device").mouseenter(function(){

		$(".route").remove();
		drawPath();
		$(".route").hide();
		target = $(this).attr('toggle');
		$('#' + target).show();
	});

});

</script>

<div class="body">


<div class="device" toggle="device1"></div>
<div class="device" toggle="device2"></div>



<div class="path"></div>



<div class="sub"></div>
<div class="sub"></div>
<div class="sub"></div>

</div>


