<html>
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="/css/style.css">
<title>404 - Page Not Found</title>
</head>
<body>
<div class="body">
	<div class="alert alert-warning" role="alert"><?php echo $message?></div>
</div>
</body>
</html>