<html>
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="/css/style.css">
<title>500 - Server Error</title>
</head>
<body>
<div class="body">
	<div class="alert alert-danger" role="alert"><?php echo $message?></div>
	<hr />
	<?php echo $table ?>
</div>
</body>
</html>