<div class="user-block">

<?php if(isset($error)): ?>
	<div class="alert alert-danger" role="alert"><?php echo $error; ?></div>
<?php endif; ?>


<form class="form-horizontal" method="post" action="">
	<?php echo $this->security->csrf_input(); ?>

	<div class="form-group">
		<label for="username" class="col-sm-3 control-label">Username: </label>
		<div class="col-sm-9">
		  <input type="text" class="form-control" id="username" name="username" placeholder="Username" value="<?php echo $username; ?>">
		</div>
	</div>

	<div class="form-group">
		<label for="password" class="col-sm-3 control-label">Password: </label>
		<div class="col-sm-9">
		  <input type="password" class="form-control" id="password" name="password" placeholder="Password" value="<?php echo $password; ?>">
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label">Remember Me: </label>
		<div class="col-sm-9">
		<input type="checkbox" class="remember-me" data-on-text="Yes" data-off-text="No" data-on-color='success' value='<?php echo $remember?>' name="remember-me" />
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-3 col-sm-9">
		<button type="submit" class="btn btn-primary">Sign in</button>
		</div>
	</div>
</form>


</div><!-- /user-block -->

<script src='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/js/bootstrap-switch.min.js'></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/css/bootstrap3/bootstrap-switch.min.css">

<script>
$(document).ready(function(){
	$("body")
		.css('background-image', "url('/img/user-bg.jpg')")
		.css('background-repeat', 'no-repeat')
		.css('background-size', '100% 100%');

	$(".remember-me")
		.bootstrapSwitch('state', $(this).val());
});
</script>